Repository twelive/JUNGLE, pull requests merged in 2023-12, with the labels that each got.

#5 Feat: 유저 git 연동 및 CRUD 코드 작업하였습니다.
  src/GlobalStyles.ts
  src/assets/common/gitlogo.svg
  src/client.ts
  src/components/LoginModal.tsx
  src/store/useAuthStore.ts
  src/store/useDataStore.ts
  tsconfig.json
Labels: 👨‍💻 Typescript, 🐼 zustand, ✨ feat, 💬dialog, ➕ add

#12 Feat/usedatahooks 온보딩페이지에 로그인모달 컴포넌트 이식 및 수정 , 데이터와 유저상태 조회 훅 완성하였습니다.
  src/components/Button/EnterButton.tsx
  src/components/LandingPage/LandingHeader.tsx
  src/components/LoginModal.tsx
  src/store/useAuthStore.ts
  src/store/useDataStore.ts
Labels: 🐛 bug, ✍ documentation, :hand: markup, 📲 supabase, ✨ feat, 💬dialog, 🔮 Onboarding, ➕ add

#15 Feat/usestoragehooks : CRUD 스토어 사용 예시 추가/ 이미지 URL 가져오는 스토어 / storage 이미지 가져오는 스토어 생성하였습니다.
  src/App.tsx
  src/store/getPbImageURL.ts
  src/store/useBucketData.ts
  src/store/useDataStore.ts
  src/store/useStorageStore.ts
Labels: 🎨 Styled-Component, 👨‍💻 Typescript, :hand: markup, 📲 supabase, 🐼 zustand, ✨ feat, ➕ add

#17 Feat/common: 공통 설정, Header 컴포넌트 작업
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/GlobalStyles.ts
  src/assets/common/arrow-scrollDown.svg
  src/assets/common/logo-border.svg
  src/assets/common/logo-title.svg
  src/components/.common.ts
  src/components/Button/HeaderButton.tsx
  src/components/Header/HeaderButtonGroup.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/Header/HeaderMenuItem.tsx
  src/components/Header/HeaderMenuItemEvent.tsx
  src/components/Header/HeaderTitle.tsx
  src/components/Logo.tsx
  src/components/MainPage/.common.tsx
  src/layout/Header.tsx
  src/layout/RootLayout.tsx
  src/pages/IntroductionPage.tsx
  src/pages/IntroductionProjectPage.tsx
  src/pages/IntroductionTeamPage.tsx
  src/routes.tsx
  src/store/.commonStore.ts
  src/store/useHeaderMenuStore.ts
Labels: 🎨 Styled-Component, 👨‍💻 Typescript, 🎆 react, :hand: markup, 🚗 react router, 🐼 zustand, ➕ add

#26 Feat/main: 메인페이지 레이아웃, 기능 작업 완료
  src/components/ArrowScrollDown.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/MainPage/Category.tsx
  src/components/MainPage/CategorySection.tsx
  src/components/ScrollDown.tsx
  src/layout/MainHeader.tsx
  src/layout/RootLayout.tsx
  src/pages/MainPage.tsx
Labels: 🎨 Styled-Component, 👨‍💻 Typescript, 🎆 react, :hand: markup, 🚗 react router, ➕ add

#39 Fix/Header: 메인페이지 -> 클릭이벤트로 카테고리 접근시 헤더 에러
  src/components/Header/HeaderMenu.tsx
  src/components/MainPage/Category.tsx
  src/layout/Header.tsx
  src/utils/getPathName.ts
Labels: 🐛 bug, 👨‍💻 Typescript, 🎆 react

#42 Feat/landing : scrollbar 제거 , 크기 조절
  src/GlobalStyles.ts
  src/components/LandingPage/SectionComponentOne.tsx
  src/pages/LandingPage.tsx
Labels: 🎨 Styled-Component, ✨ feat

#43 Feat/job : JobSeekPage 1차 완성
  src/GlobalStyles.ts
  src/assets/job/job-banner.svg
  src/components/JobPage/.common.tsx
  src/components/JobPage/JobHeaderItem.tsx
  src/components/JobPage/JobInterviewBox.tsx
  src/components/JobPage/JobSeekBox.tsx
  src/layout/Footer.tsx
  src/pages/JobInterviewPage.tsx
  src/pages/JobPage.tsx
  src/pages/JobSeekPage.tsx
  src/routes.tsx
Labels: 🎨 Styled-Component, 👨‍💻 Typescript, :hand: markup, 📲 supabase, ✨ feat

#44 Feat/CommunityPage/banner: 커뮤니티 페이지 배너 스와이퍼 및 그리드 스와이퍼 사용
  package.json
  pnpm-lock.yaml
  src/GlobalStyles.ts
  src/assets/community/community-banner1.svg
  src/assets/community/community-banner2.svg
  src/assets/community/community-banner3.svg
  src/assets/community/community-js.svg
  src/assets/community/community-next.js.svg
  src/assets/community/community-react.svg
  src/assets/community/community-svelte.svg
  src/assets/community/community-ts.svg
  src/assets/community/community-vue.svg
  src/pages/CommunityCreatePage.tsx
  src/pages/CommunityPage.tsx
  src/routes.tsx
Labels: 🎨 Styled-Component, 👨‍💻 Typescript, 🎆 react, :hand: markup, 🚗 react router, 📲 supabase, 🎏 Swiper, ✨ feat, ➕ add

#45 Feat: StudyPage 도서 추천 파트 컴포넌트 분류 및 supabase GET 확인 완료
  src/assets/common/activelike.svg
  src/assets/common/inactivelike.svg
  src/components/StudyPage/CommonStudyComponent.tsx
  src/components/StudyPage/StudyTitleGroup.tsx
  src/components/StudyPage/TagButton.tsx
  src/hooks/Auth.tsx
  src/pages/StudyPage.tsx
  src/store/useTagStore.ts
Labels: 🎨 Styled-Component, 👨‍💻 Typescript, 🎆 react, :hand: markup, 📲 supabase, 🐼 zustand, ✨ feat, ➕ add, ❤ bookmark

#58 Feat/MyPage/Main: 인증 유저 정보를 통한 사용자 이름, 알맞은 경로 출력
  src/components/Header/HeaderMenuItem.tsx
  src/components/MainPage/Category.tsx
  src/components/MainPage/CategorySection.tsx
  src/components/MyPage/ProfileSection.tsx
  src/components/MyPage/ResumeLink.tsx
  src/layout/RootLayout.tsx
  src/routes.tsx
  src/utils/getUserName.ts
Labels: 🎆 react, 🚗 react router, 📲 supabase, ✨ feat, ➕ add

#60 Feat: 반응형 구현 위한 미디어 쿼리, 스타일 작성
  src/App.tsx
  src/GlobalStyles.ts
  src/theme.ts
Labels: 🎨 Styled-Component, 🎆 react, ➕ add

#66 Fix: 메인페이지 카테고리 -> 내활동 페이지 접근 에러 해결
  src/components/Header/HeaderMenu.tsx
  src/components/Header/HeaderMenuItem.tsx
  src/components/MyPage/ProfileSection.tsx
Labels: 🐛 bug, 🎆 react, 🚗 react router, 📲 supabase, 🐼 zustand

#71 Feat: 반응형 margin 고정형 -> % 로 수정
  src/GlobalStyles.ts
Labels: 🎨 Styled-Component, ✨ feat, ➕ add, :rescue_worker_helmet: responsive

#84 Feat: HeaderButton 로그아웃 연결 하였습니다.
  src/components/Button/HeaderButton.tsx
  src/components/Header/HeaderButtonGroup.tsx
Labels: 🎨 Styled-Component, 👨‍💻 Typescript, 🐼 zustand, ✨ feat, ➕ add

#85 Feat/Footer: 반응형 구현
  src/layout/Footer.tsx
Labels: 🎨 Styled-Component, ✨ feat, :rescue_worker_helmet: responsive

#86 Feat/Main: 반응형 구현
  src/components/MainPage/Category.tsx
  src/components/MainPage/CategorySection.tsx
  src/pages/MainPage.tsx
Labels: 🎨 Styled-Component, ✨ feat, ➕ add, :rescue_worker_helmet: responsive

#90 Feat/community: 커뮤니티 메인페이지 리액트쿼리사용
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/community/community-banner1.svg
  src/assets/community/community-banner2.svg
  src/assets/community/community-banner3.svg
  src/client.ts
  src/pages/CommunityDetailPage.tsx
  src/pages/CommunityPage.tsx
  src/routes.tsx
  src/store/useDataStore.ts
  src/store/useEmailStore.ts
  src/types/CommunityProject.ts
  src/types/CommunityStudy.ts
  src/types/Users.ts
  src/types/database.ts
  supabase/.gitignore
  supabase/config.toml
  supabase/seed.sql
Labels: 🎨 Styled-Component, 🧰 Refactor, 👨‍💻 Typescript, 🎆 react, :hand: markup, 📲 supabase, 🎏 Swiper, ✨ feat, ➕ add

#91 Feat/MyPage: 반응형 구현 완료
  src/assets/common/arrow-clickLink.svg
  src/components/MainPage/Category.tsx
  src/components/MyPage/BookMarkItem.tsx
  src/components/MyPage/BookMarkLink.tsx
  src/components/MyPage/BookMarkList.tsx
  src/components/MyPage/BookMarkModal.tsx
  src/components/MyPage/PointSection.tsx
  src/components/MyPage/Profile.tsx
  src/components/MyPage/ProfileSection.tsx
  src/components/MyPage/ResumeLink.tsx
  src/components/MyPage/WritingCategory.tsx
  src/pages/MyPage.tsx
  src/store/useModalHeight.ts
Labels: 🎨 Styled-Component, :hand: markup, ✨ feat, 💬dialog, ➕ add, :rescue_worker_helmet: responsive

#92 Feat/job : JobInterviewPage, JobCodingTestPage 제작
  src/components/JobPage/AddComment.tsx
  src/components/JobPage/CommentSaveBox.tsx
  src/components/JobPage/DeleteButton.tsx
  src/components/JobPage/JobCodingTestBox.tsx
  src/components/JobPage/JobHeaderCreateButton.tsx
  src/components/JobPage/JobHeaderItem.tsx
  src/components/JobPage/JobInterviewBox.tsx
  src/pages/JobCodingTestItemPage.tsx
  src/pages/JobCodingTestPage.tsx
  src/pages/JobInterviewItemPage.tsx
  src/pages/JobInterviewPage.tsx
  src/routes.tsx
  src/store/useCommentStore.ts
  src/store/useDataStore.ts
Labels: 🎨 Styled-Component, 🧰 Refactor, 👨‍💻 Typescript, :hand: markup, 📲 supabase, 🐼 zustand, ✨ feat, ➕ add, :rescue_worker_helmet: responsive

#98 Feat/Header : 헤더 컴포넌트 반응형 구현
  src/components/Button/HeaderButton.tsx
  src/components/Header/HeaderButtonGroup.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/Header/HeaderMenuItem.tsx
  src/components/Header/HeaderTitle.tsx
  src/components/Logo.tsx
  src/components/ScrollDown.tsx
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/layout/MainHeader.tsx
  src/store/useHeaderMenuStore.ts
Labels: 🎨 Styled-Component, :rescue_worker_helmet: responsive

#99 Feat/Introduction/Team : 팀 소개 페이지 레이아웃, 반응형 작업
  src/assets/Introduction/cereallover.svg
  src/assets/Introduction/seojinman.svg
  src/assets/Introduction/sy0725.svg
  src/assets/Introduction/uniS2.svg
  src/components/IntroductionPage/.common.tsx
  src/components/IntroductionPage/Schedule.tsx
  src/components/IntroductionPage/TeamPeople.tsx
  src/pages/IntroductionTeamPage.tsx
Labels: 🎨 Styled-Component, 🎆 react, :hand: markup, ➕ add, :rescue_worker_helmet: responsive

#100 Feat/Introduction/Project : 프로젝트 소개 페이지 레이아웃, 반응형 구현
  src/assets/common/twellive.svg
  src/components/IntroductionPage/ProjectExplanation.tsx
  src/components/IntroductionPage/Schedule.tsx
  src/pages/IntroductionProjectPage.tsx
Labels: 🎨 Styled-Component, 🎆 react, :hand: markup, ➕ add, :rescue_worker_helmet: responsive

#102 Fix/MyPage : 마이페이지 닉네임 에러
  src/components/MyPage/ProfileSection.tsx
Labels: 🐛 bug, 🎆 react

#101 Fix/Header : 주소와 헤더가 일치하지 않는 에러 해결 작업
  src/components/Header/HeaderMenu.tsx
  src/layout/Header.tsx
  src/store/useHeaderMenuStore.ts
Labels: 🐛 bug, 🎆 react, 🚗 react router, 🐼 zustand, ✨ feat

#105 Feat: LikeButton 좋아요 기능 구현 완료/ 도서 추천 파트 적용 완료하였습니다.
  src/components/StudyPage/LikeButton.tsx
  src/pages/StudyPage.tsx
Labels: 👨‍💻 Typescript, 🎆 react, 📲 supabase, 🐼 zustand, ✨ feat, ➕ add

#109 Feat/job : 댓글 기능 구현중
  src/components/JobPage/AddComment.tsx
  src/components/JobPage/CommentSaveBox.tsx
  src/components/JobPage/DeleteButton.tsx
  src/store/useAuthStore.ts
  src/store/useCommentStore.ts
Labels: 🎨 Styled-Component, 🧰 Refactor, 👨‍💻 Typescript, :hand: markup, 📲 supabase, 🐼 zustand, ✨ feat, ➕ add

#111 Feat/Introduction/Team: 팀원 hover 시 링크 이벤트 component 구현
  src/assets/Introduction/MyoungHwaShin.svg
  src/components/IntroductionPage/GithubLink.tsx
  src/components/IntroductionPage/TeamPeople.tsx
  src/pages/IntroductionTeamPage.tsx
  src/utils/debounce.ts
  src/utils/getGithubLink.ts
Labels: 🎨 Styled-Component, 🎆 react, :hand: markup, ✨ feat, :rescue_worker_helmet: responsive

#112 Feat/Bookmark: 북마크 정보 렌더링 테스트
  src/components/MyPage/BookMarkList.tsx
  src/components/MyPage/WritingCategory.tsx
  src/types/BookMarks.ts
Labels: ✍ documentation, 🎆 react, 📲 supabase, ➕ add, ❤ bookmark, 📕 tanstack query

#113 Feat/Common: 로딩 컴포넌트, 에러 페이지 작업
  src/App.tsx
  src/assets/common/error.webp
  src/components/Loading.tsx
  src/layout/RootLayout.tsx
  src/pages/ErrorPage.tsx
  src/routes.tsx
Labels: 🎆 react, :hand: markup, 🚗 react router, ➕ add

#114 Fix/Mypage: 유저 정보 로딩 undefined 에러
  src/api/.common.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/MainPage/CategorySection.tsx
  src/components/MyPage/ProfileSection.tsx
  src/components/MyPage/ResumeLink.tsx
Labels: 🐛 bug, 🎆 react, 🚗 react router, 💡 question, 🐼 zustand, 📕 tanstack query

#116 Feat/community : 커뮤니티 모집하기 클릭 시 글 작성 페이지 작성
  src/pages/CommunityCreatePage.tsx
  src/pages/CommunityPage.tsx
  src/store/useCreateStore.ts
  src/types/db.ts
Labels: 👨‍💻 Typescript, 🎆 react, :hand: markup, 📲 supabase, ✨ feat, ➕ add

#120 Feat:좋아요버튼, 태그버튼 타입 추가/기술 디깅 파트 추가 마크업 완료하였습니다.
  src/components/StudyPage/LikeButton.tsx
  src/components/StudyPage/TagButton.tsx
  src/pages/StudyPage.tsx
Labels: 🎨 Styled-Component, 👨‍💻 Typescript, 📲 supabase, ➕ add

#121 Feat: 북마크 기능 구현 완료하였습니다.
  src/assets/common/bookmarkblack.svg
  src/assets/common/bookmarkbluefilled.svg
  src/assets/common/bookmarkwhite.svg
  src/components/StudyPage/BookMarkButton.tsx
Labels: 👨‍💻 Typescript, 🎆 react, 📲 supabase, 🐼 zustand, ➕ add, ❤ bookmark

#123 Feat/Mypage/Profile: 프로필 이미지 로딩, 수정 기능
  src/assets/common/edit.svg
  src/components/Button/EditButton.tsx
  src/components/JobPage/AddComment.tsx
  src/components/MyPage/BookMarkList.tsx
  src/components/MyPage/Profile.tsx
  src/components/MyPage/ProfileSection.tsx
  src/pages/CommunityCreatePage.tsx
  src/pages/StudyPage.tsx
Labels: 🎨 Styled-Component, 👨‍💻 Typescript, 🎆 react, 📲 supabase, ➕ add, :rescue_worker_helmet: responsive

#125 Feat/createpage: DatePicker 및 프로젝트/스터디 삭제 구현
  package.json
  pnpm-lock.yaml
  src/components/StudyPage/LikeButton.tsx
  src/pages/CommunityCreatePage.tsx
  src/pages/CommunityDetailPage.tsx
  src/types/database.ts
Labels: 👨‍💻 Typescript, 🎆 react, 📲 supabase, ✨ feat, ➕ add, 📕 tanstack query

#129 Feat/Mypage/Profile: useQuery 이용한 프로필 수정 기능 속도 Test
  src/App.tsx
  src/components/MyPage/Profile.tsx
  src/utils/getPbSrc.ts
Labels: 🐛 bug, 📕 tanstack query

#133 Feat/Common: 절대 경로 반영
  src/client.ts
  src/pages/CommunityPage/CommunityPage.tsx
Labels: ➕ add

#135 Fea: 기술 디깅 파트 마크업 및 컴포넌트 작업하였습니다
  src/components/StudyPage/StackDiggingItem.tsx
  src/pages/StackDetailPage.tsx
  src/pages/StackListlPage.tsx
  src/pages/StackNewPage.tsx
  src/pages/StudyPage/StudyPage.tsx
Labels: 👨‍💻 Typescript, 🎆 react, :hand: markup, 📲 supabase, 🐼 zustand, ➕ add

#136 Feat: 기술디깅 파트 라우터와 버튼 일부 수정 하였습니다.
  src/components/StudyPage/TagButtonComponent.tsx
  src/routes.tsx
Labels: 🎆 react, :hand: markup, 🚗 react router, ✨ feat, ➕ add

#138 Feat/Common: 로딩 컴포넌트 작업
  src/App.tsx
  src/components/Loading.tsx
Labels: 🎆 react, :hand: markup, 🚗 react router, ➕ add

#139 Feat/job : 경로 수정 후 merge
  src/pages/JobPage/JobInterviewPage.tsx
  src/store/useCommentStore.ts
Labels: ➕ add

#141 Feat: delete기능 구현 및 로그인한 유저와 글작성자가 같을 경우에만 수정및 삭제 가능
  src/pages/CommunityPage/CommunityDetailPage.tsx
Labels: 👨‍💻 Typescript, 🎆 react, 📲 supabase, ✨ feat, ➕ add, 📕 tanstack query

#142 Feat:StackListlPage 라우터 수정/ StackNewPage 새글 작성 페이지 완성하였습니다.
  src/pages/StackListlPage.tsx
  src/pages/StackNewPage.tsx
Labels: :hand: markup, 📲 supabase, ✨ feat, ➕ add

#143 Feat: StackDiggingPart 타입스크립트 적용 및 기본 마크업 및 기능 완료하였습니다.
  src/App.tsx
  src/components/LoginModal.tsx
  src/components/StudyPage/StackDiggingItem.tsx
  src/components/StudyPage/StudyTitleGroup.tsx
  src/pages/StackDetailPage.tsx
  src/pages/StackListlPage.tsx
  src/pages/StackNewPage.tsx
  src/routes.tsx
  src/store/useAuthStore.ts
  src/types/StackDigging.ts
  src/types/StackDiggingDTO.ts
Labels: ✍ documentation, 👨‍💻 Typescript, :hand: markup, 📲 supabase, 🐼 zustand, ✨ feat, ➕ add

#144 Feat/landing/job - 리팩토링
  src/App.tsx
  src/assets/job/job-banner.svg
  src/assets/job/job-banner1.svg
  src/assets/job/job-banner2.svg
  src/assets/job/job-banner3.svg
  src/components/Button/EnterButton.tsx
  src/components/JobPage/AddComment.tsx
  src/components/JobPage/CodingTestBookmark.tsx
  src/components/JobPage/CreateButton.tsx
  src/components/JobPage/InterviewBookmark.tsx
  src/components/JobPage/ItemDeleteButton.tsx
  src/components/JobPage/JobCodingAddComment.tsx
  src/components/JobPage/JobCodingCommentSaveBox.tsx
  src/components/JobPage/JobCodingTestBox.tsx
  src/components/JobPage/JobHeaderCreateButton.tsx
  src/components/JobPage/JobInterviewBox.tsx
  src/components/JobPage/ScrollBottomButton.tsx
  src/components/LandingPage/SectionComponentFive.tsx
  src/components/LandingPage/SectionComponentFour.tsx
  src/components/LandingPage/SectionComponentOne.tsx
  src/components/LandingPage/SectionComponentThree.tsx
  src/components/LandingPage/SectionComponentTwo.tsx
  src/components/LandingPage/SectionMotionDiv.tsx
  src/components/LandingPage/SectionScrollDownButton.tsx
  src/components/LandingPage/SectionScrollUpButton.tsx
  src/components/LandingPage/SectionThreeImgBox.tsx
  src/components/SwiperComponet.tsx
  src/pages/JobPage/JobCodingTestCreatePage.tsx
  src/pages/JobPage/JobCodingTestPage.tsx
  src/pages/JobPage/JobInterviewCreatePage.tsx
  src/pages/JobPage/JobInterviewPage.tsx
  src/pages/JobPage/JobSeekPage.tsx
  src/store/useBucketData.ts
  src/store/useCodingCommentStore.ts
  src/store/useCodingTestCreateStore.ts
  src/store/useCommentStore.ts
  src/store/useInterviewCreateStore.ts
  src/store/useLandingStore.ts
  src/utils/createChildVariants.ts
Labels: 🎨 Styled-Component, 👨‍💻 Typescript, :hand: markup, 🚗 react router, 🎈 Framer-motion, 📲 supabase, 🎏 Swiper, 🐼 zustand, ✨ feat, ➕ add, ❤ bookmark, :rescue_worker_helmet: responsive

#145 Feat/createpagestyle: 주석 제거 및 스타일링
  src/assets/community/community-banner1.svg
  src/assets/community/community-banner2.svg
  src/assets/community/community-banner3.svg
  src/pages/CommunityPage/CommunityCreatePage.tsx
  src/pages/CommunityPage/CommunityDetailPage.tsx
  src/pages/CommunityPage/CommunityPage.tsx
Labels: 🎨 Styled-Component, 🧰 Refactor, 🎆 react

#146 Docs : README 초안 작성
  README.md
Labels: ✍ documentation, :hand: markup

#153 Refactor: 에러 디버깅, 웹폰트 용량 문제 해결
  index.html
  src/pages/MainPage.tsx
  src/store/useAuthStore.ts
Labels: 🧰 Refactor

#154 Fix: redirect 경로 재수정 - test2
  src/store/useAuthStore.ts
Labels: 🧰 Refactor

#155 Feat/Mypage: 작성한 글 렌더링
  src/api/useWrittingData.tsx
  src/components/MainPage/Category.tsx
  src/components/MyPage/WritingCategory.tsx
Labels: 📲 supabase, ➕ add, 📕 tanstack query

#160 Init: 리디렉션 URL 설정 Test 1
  src/store/useAuthStore.ts
Labels: ➕ add

#161 Init: 리디렉션 URL 설정 Test 2
  src/store/useAuthStore.ts
Labels: ➕ add

#162 Refactor: 헤더 경로 수정
  src/layout/RootLayout.tsx
Labels: 🐛 bug

#163 Refactor: 프로모션, 개발 환경 리디렉션 경로 최종 설정
  src/store/useAuthStore.ts
Labels: ➕ add

#167 Refactor: 라이브러리 정리
  package.json
  pnpm-lock.yaml
Labels: 🧰 Refactor

#170 Feat/stacknewpageaddedconsole 에러 처리를 위한 콘솔을 추가하였습니다.
  src/App.tsx
  src/pages/StackDetailPage.tsx
  src/pages/StackNewPage.tsx
  src/store/useDataStore.ts
Labels: 🐛 bug, ➕ add

#171 Refactor: 에러, 리팩토링
  src/components/LandingPage/SectionComponentOne.tsx
  src/components/MyPage/ResumeLink.tsx
  src/components/MyPage/WritingCategory.tsx
  src/store/useHeaderMenuStore.ts
Labels: 🐛 bug, 🧰 Refactor, ➕ add

#183 Refactor : 1차 반응형 리팩토링
  src/components/LandingPage/LandingHeader.tsx
  src/components/LandingPage/SectionComponentFive.tsx
  src/components/LandingPage/SectionComponentFour.tsx
  src/components/LandingPage/SectionComponentOne.tsx
  src/components/LandingPage/SectionComponentThree.tsx
  src/components/LandingPage/SectionComponentTwo.tsx
  src/components/LandingPage/SectionScrollDownButton.tsx
  src/components/LandingPage/SectionScrollUpButton.tsx
  src/components/LandingPage/SectionThreeImgBox.tsx
Labels: 🧰 Refactor

#185 Refactor : 2차 반응형 리펙토링
  src/components/LandingPage/SectionComponentThree.tsx
  src/components/LandingPage/SectionScrollUpButton.tsx
  src/components/LandingPage/SectionThreeImgBox.tsx
Labels: 🧰 Refactor

#186 Feat/job - JobPage 1차 리팩토링
  src/components/Button/EnterButton.tsx
  src/components/JobPage/CreateButton.tsx
  src/components/JobPage/DeleteButton.tsx
  src/components/JobPage/ItemDeleteButton.tsx
  src/components/JobPage/JobCodingAddComment.tsx
  src/components/JobPage/JobCodingCommentSaveBox.tsx
  src/components/JobPage/JobCodingDeleteButton.tsx
  src/components/JobPage/JobCodingTestBookmark.tsx
  src/components/JobPage/JobCodingTestBox.tsx
  src/components/JobPage/JobHeaderCreateButton.tsx
  src/components/JobPage/JobHeaderItem.tsx
  src/components/JobPage/JobInterviewAddComment.tsx
  src/components/JobPage/JobInterviewBookmark.tsx
  src/components/JobPage/JobInterviewBox.tsx
  src/components/JobPage/JobInterviewCommentSaveBox.tsx
  src/components/JobPage/JobSeekBox.tsx
  src/components/JobPage/NavButton.tsx
  src/components/LandingPage/LandingHeader.tsx
  src/components/LandingPage/SectionComponentFive.tsx
  src/components/LandingPage/SectionComponentFour.tsx
  src/components/LandingPage/SectionComponentOne.tsx
  src/components/LandingPage/SectionComponentThree.tsx
  src/components/LandingPage/SectionComponentTwo.tsx
  src/components/LandingPage/SectionScrollDownButton.tsx
  src/components/LandingPage/SectionScrollUpButton.tsx
  src/components/LandingPage/SectionThreeImgBox.tsx
  src/pages/JobPage/JobCodingTestCreatePage.tsx
  src/pages/JobPage/JobCodingTestItemDeleteButton.tsx
  src/pages/JobPage/JobCodingTestItemPage.tsx
  src/pages/JobPage/JobCodingTestPage.tsx
  src/pages/JobPage/JobInterviewCreatePage.tsx
  src/pages/JobPage/JobInterviewItemPage.tsx
  src/pages/JobPage/JobInterviewPage.tsx
  src/pages/JobPage/JobSeekPage.tsx
  src/store/useInterviewCommentStore.ts
Labels: 🧰 Refactor
