Repository twelive/JUNGLE, pull requests merged in 2024-01, with the labels that each got.

#199 Develop -> main: 리팩토링 작업 merge
  src/components/Button/EnterButton.tsx
  src/components/JobPage/CreateButton.tsx
  src/components/JobPage/DeleteButton.tsx
  src/components/JobPage/ItemDeleteButton.tsx
  src/components/JobPage/JobCodingAddComment.tsx
  src/components/JobPage/JobCodingCommentSaveBox.tsx
  src/components/JobPage/JobCodingDeleteButton.tsx
  src/components/JobPage/JobCodingTestBookmark.tsx
  src/components/JobPage/JobCodingTestBox.tsx
  src/components/JobPage/JobHeaderCreateButton.tsx
  src/components/JobPage/JobHeaderItem.tsx
  src/components/JobPage/JobInterviewAddComment.tsx
  src/components/JobPage/JobInterviewBookmark.tsx
  src/components/JobPage/JobInterviewBox.tsx
  src/components/JobPage/JobInterviewCommentSaveBox.tsx
  src/components/JobPage/JobSeekBox.tsx
  src/components/JobPage/NavButton.tsx
  src/components/LandingPage/LandingHeader.tsx
  src/components/LandingPage/SectionComponentFive.tsx
  src/components/LandingPage/SectionComponentFour.tsx
  src/components/LandingPage/SectionComponentOne.tsx
  src/components/LandingPage/SectionComponentThree.tsx
  src/components/LandingPage/SectionComponentTwo.tsx
  src/components/LandingPage/SectionScrollDownButton.tsx
  src/components/LandingPage/SectionScrollUpButton.tsx
  src/components/LandingPage/SectionThreeImgBox.tsx
  src/pages/JobPage/JobCodingTestCreatePage.tsx
  src/pages/JobPage/JobCodingTestItemDeleteButton.tsx
  src/pages/JobPage/JobCodingTestItemPage.tsx
  src/pages/JobPage/JobCodingTestPage.tsx
  src/pages/JobPage/JobInterviewCreatePage.tsx
  src/pages/JobPage/JobInterviewItemPage.tsx
  src/pages/JobPage/JobInterviewPage.tsx
  src/pages/JobPage/JobSeekPage.tsx
  src/store/useInterviewCommentStore.ts
Labels: 🧰 Refactor

#203 Feat/job - scroll 개선
  src/components/LandingPage/ SectionScroll.tsx
  src/components/LandingPage/SectionComponentFive.tsx
  src/components/LandingPage/SectionComponentFour.tsx
  src/components/LandingPage/SectionComponentOne.tsx
  src/components/LandingPage/SectionComponentThree.tsx
  src/components/LandingPage/SectionComponentTwo.tsx
Labels: 🧰 Refactor, ✨ feat

#204 Feat/job - 경로수정
  src/components/LandingPage/SectionComponentFive.tsx
  src/components/LandingPage/SectionComponentFour.tsx
  src/components/LandingPage/SectionComponentOne.tsx
  src/components/LandingPage/SectionComponentThree.tsx
  src/components/LandingPage/SectionComponentTwo.tsx
  src/components/LandingPage/SectionScroll.tsx
Labels: 🧰 Refactor

#200 Refactor: Main - UI 및 구성요소명 수정
  src/pages/MainPage.tsx
Labels: 🎨 Styled-Component, 🧰 Refactor

#206 Refactor/rem: Community, Detail,Create Page px -> rem 으로 변경
  src/pages/CommunityPage/CommunityCreatePage.tsx
  src/pages/CommunityPage/CommunityDetailPage.tsx
  src/pages/CommunityPage/CommunityPage.tsx
Labels: 🎨 Styled-Component

#208 Feat/job - Styled Component 네이밍 수정
  src/components/Button/EnterButton.tsx
  src/components/JobPage/CreateButton.tsx
  src/components/JobPage/DeleteButton.tsx
  src/components/JobPage/ItemDeleteButton.tsx
  src/components/JobPage/JobCodingAddComment.tsx
  src/components/JobPage/JobCodingCommentSaveBox.tsx
  src/components/JobPage/JobCodingDeleteButton.tsx
  src/components/JobPage/JobCodingTestBookmark.tsx
  src/components/JobPage/JobCodingTestBox.tsx
  src/components/JobPage/JobHeaderCreateButton.tsx
  src/components/JobPage/JobHeaderItem.tsx
  src/components/JobPage/JobInterviewAddComment.tsx
  src/components/JobPage/JobInterviewBookmark.tsx
  src/components/JobPage/JobInterviewBox.tsx
  src/components/JobPage/JobInterviewCommentSaveBox.tsx
  src/components/JobPage/JobSeekBox.tsx
  src/components/JobPage/NavButton.tsx
  src/components/JobPage/ScrollBottomButton.tsx
  src/components/JobPage/ScrollTopButton.tsx
  src/components/LandingPage/LandingHeader.tsx
  src/components/LandingPage/SectionComponentFive.tsx
  src/components/LandingPage/SectionComponentFour.tsx
  src/components/LandingPage/SectionComponentOne.tsx
  src/components/LandingPage/SectionComponentThree.tsx
  src/components/LandingPage/SectionComponentTwo.tsx
  src/components/LandingPage/SectionScrollDownButton.tsx
  src/components/LandingPage/SectionScrollUpButton.tsx
  src/components/LandingPage/SectionThreeImgBox.tsx
  src/pages/JobPage/JobCodingTestCreatePage.tsx
  src/pages/JobPage/JobCodingTestItemPage.tsx
  src/pages/JobPage/JobCodingTestPage.tsx
  src/pages/JobPage/JobInterviewCreatePage.tsx
  src/pages/JobPage/JobInterviewItemPage.tsx
  src/pages/JobPage/JobInterviewPage.tsx
  src/pages/JobPage/JobSeekPage.tsx
  src/pages/LandingPage/LandingPage.tsx
Labels: 🎨 Styled-Component, 🧰 Refactor

#210 Refactor/common: 리팩토링: 작업 파트 내 Styled-Components 요소 네이밍 변경
  src/components/Button/BackButton.tsx
  src/components/Button/EditButton.tsx
  src/components/Button/EnterButton.tsx
  src/components/Button/HeaderButton.tsx
  src/components/Header/HeaderButtonGroup.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/Header/HeaderMenuItem.tsx
  src/components/Header/HeaderTitle.tsx
  src/components/IntroductionPage/GithubLink.tsx
  src/components/IntroductionPage/ProjectExplanation.tsx
  src/components/IntroductionPage/Schedule.tsx
  src/components/IntroductionPage/TeamPeople.tsx
  src/components/Loading.tsx
  src/components/Logo.tsx
  src/components/MainPage/Category.tsx
  src/components/MainPage/CategorySection.tsx
  src/components/MyPage/BookMarkDialog.tsx
  src/components/MyPage/BookMarkItem.tsx
  src/components/MyPage/BookMarkLink.tsx
  src/components/MyPage/BookMarkList.tsx
  src/components/MyPage/PointSection.tsx
  src/components/MyPage/Profile.tsx
  src/components/MyPage/ProfileSection.tsx
  src/components/MyPage/ResumeLink.tsx
  src/components/MyPage/WritingCategory.tsx
  src/components/ScrollDown.tsx
  src/components/StudyPage/BookMarkButton.tsx
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/layout/MainHeader.tsx
  src/pages/ErrorPage.tsx
  src/pages/IntroductionPage/IntroductionProjectPage.tsx
  src/pages/IntroductionPage/IntroductionTeamPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/MyResumePage.tsx
Labels: 🎨 Styled-Component, 🧰 Refactor

#212 Refactor/studypart : refactoring 진행 styled-component 명명 컨벤션 규칙따라 수정 / border 단위 수정 / 외부에 있던 관련 페이지 study 폴더내 이동
  src/components/StudyPage/LikeButton.tsx
  src/components/StudyPage/StackDiggingContentsContainer.tsx
  src/components/StudyPage/StackDiggingItem.tsx
  src/components/StudyPage/StackDiggingNameContainer.tsx
  src/components/StudyPage/StudyTitleGroup.tsx
  src/components/StudyPage/TagButtonComponent.tsx
  src/pages/StudyPage/StackDetailPage.tsx
  src/pages/StudyPage/StackListlPage.tsx
  src/pages/StudyPage/StackNewPage.tsx
  src/pages/StudyPage/StudyPage.tsx
  src/routes.tsx
Labels: ✍ documentation, 🎨 Styled-Component, 👨‍💻 Typescript, :hand: markup, ➕ add

#213 Feat/job : 반응형 UI 수정
  src/components/JobPage/JobCodingTestBox.tsx
  src/components/JobPage/JobInterviewBox.tsx
  src/components/LandingPage/SectionMotionDiv.tsx
  src/layout/Footer.tsx
Labels: 🎨 Styled-Component, 🧰 Refactor, :rescue_worker_helmet: responsive

#217 Refactor/Community part : refactoring 진행 styled-component 명명 컨벤션 규칙따라 수정 / border 단위 수정 / Footer 변경
  src/assets/community/community-happynewyear.svg
  src/assets/community/community-jobdata.svg
  src/assets/community/community-jungle.svg
  src/components/CommunityPage/.common.tsx
  src/components/CommunityPage/CommunityCreateAuthorInfo.tsx
  src/components/CommunityPage/CommunityCreateDeadline.tsx
  src/components/CommunityPage/CommunityCreateDetail.tsx
  src/components/CommunityPage/CommunityCreateIntroduction.tsx
  src/components/CommunityPage/CommunityDetailItem.tsx
  src/components/CommunityPage/CommunityDetailLogic.tsx
  src/components/CommunityPage/CommunityItemCard.tsx
  src/hooks/useDataFetching.tsx
  src/layout/Footer.tsx
  src/pages/CommunityPage/CommunityCreatePage.tsx
  src/pages/CommunityPage/CommunityDetailPage.tsx
  src/pages/CommunityPage/CommunityPage.tsx
Labels: 🎨 Styled-Component, 🧰 Refactor, 👨‍💻 Typescript, :hand: markup, ✨ feat, ➕ add

#228 Refactor: border px 단위 유지, 코드 정리
  src/components/Button/EditButton.tsx
  src/components/Button/HeaderButton.tsx
  src/components/CancelImg.tsx
  src/components/Header/HeaderButtonGroup.tsx
  src/components/Header/HeaderMenuItem.tsx
  src/components/IntroductionPage/GithubLink.tsx
  src/components/IntroductionPage/ProjectExplanation.tsx
  src/components/IntroductionPage/Schedule.tsx
  src/components/IntroductionPage/TeamPeople.tsx
  src/components/MainPage/CategorySection.tsx
  src/components/MyPage/BookMarkDialog.tsx
  src/components/MyPage/BookMarkLink.tsx
  src/components/MyPage/BookMarkListData.tsx
  src/components/MyPage/PointSection.tsx
  src/components/MyPage/Profile.tsx
  src/components/MyPage/ProfileSection.tsx
  src/components/MyPage/ResumeLink.tsx
  src/components/MyPage/WritingCategory.tsx
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/pages/ErrorPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/MyResumePage.tsx
  src/pages/MyResumeDetailPage.tsx
  src/routes.tsx
Labels: 🧰 Refactor

#234 Feat/profile: 프로필 업데이트 로직 중복 update -> delete + 새로 update로 변경
  src/api/getImageUrlRealtimeUpload.ts
  src/components/MyPage/Profile.tsx
  src/components/MyPage/WritingCategory.tsx
  src/components/MyPage/WritingCategoryTag.tsx
  src/pages/MyPage/MyResumeDetailPage.tsx
  src/pages/MyPage/MyResumePage.tsx
  src/routes.tsx
  src/store/getPbImageURL.ts
  src/types/ResumeNew.ts
  src/types/database.ts
Labels: 🎆 react, ✨ feat
