Repository twelive/JUNGLE, pull requests merged in 2024-02, with the labels that each got.

#239 Refactor/studypart 스터디 페이지 스택 디깅 디테일 페이지에 댓글 기능 추가하였습니다.
  src/components/StudyPage/CommentItem.tsx
  src/pages/StudyPage/StackDetailPage.tsx
  src/pages/StudyPage/StudyPage.tsx
  src/store/useStackDiggingCommentStore.ts
  src/types/StackCommentDTO.ts
Labels: 🐛 bug, 🎨 Styled-Component, 🧰 Refactor, 👨‍💻 Typescript, 🎆 react, 📲 supabase, ✨ feat, ➕ add

#240 Feat/Resume: 이력서 작성 페이지 기본 UI, Create 작업 완료
  src/assets/mypage/resume-activity.svg
  src/assets/mypage/resume-blog.svg
  src/assets/mypage/resume-github.svg
  src/assets/mypage/resume-link.svg
  src/assets/mypage/resume-mail.svg
  src/assets/mypage/resume-me.svg
  src/assets/mypage/resume-personalStatement.svg
  src/assets/mypage/resume-phone.svg
  src/assets/mypage/resume-plus.svg
  src/assets/mypage/resume-portfolio.svg
  src/assets/mypage/resume-project.svg
  src/assets/mypage/resume-stack.svg
  src/components/MyPage/ResumeInfoIcon.tsx
  src/components/MyPage/ResumeLink.tsx
  src/components/MyPage/ResumeSubheading.tsx
  src/layout/RootLayout.tsx
  src/pages/MyPage/MyResumeDetailPage.tsx
  src/pages/MyPage/ResumeListPage.tsx
  src/pages/MyPage/ResumeNewPage.tsx
  src/pages/MyResumeDetailPage.tsx
  src/routes.tsx
  src/store/useHeaderMenuStore.ts
Labels: 🎨 Styled-Component, 👨‍💻 Typescript, 🎆 react, :hand: markup, ✨ feat

#250 Refactor/studypart : 리스트 페이지 목록 스타일 변경과 댓글 UI 개선하였습니다.
  src/components/StudyPage/CommentItem.tsx
  src/components/StudyPage/StackDiggingItem.tsx
  src/pages/StudyPage/StackListlPage.tsx
  src/pages/StudyPage/StudyPage.tsx
Labels: 🎨 Styled-Component, 🧰 Refactor, 👨‍💻 Typescript, 🎆 react, 📲 supabase, ➕ add

#251 Design: 작성글 border 레이아웃 변경
  src/components/MyPage/BookMarkItem.tsx
  src/components/MyPage/WritingCategory.tsx
Labels: 🎨 Styled-Component

#252 Feat: 쿼리 북마크 개선한 버튼입니다
  src/components/StudyPage/QueryBookMarkButton.tsx
Labels: 🎨 Styled-Component, 👨‍💻 Typescript, 🎆 react, 📲 supabase, ✨ feat, ❤ bookmark
